apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: analytics-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: analytics-deployment
  minReplicas: {{ .Values.hpaanalytics.minReplicas }}
  maxReplicas: {{ .Values.hpaanalytics.maxReplicas }}
  targetCPUUtilizationPercentage: {{ .Values.hpaanalytics.cpuUtilization }}