apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: core-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: core-deployment
  minReplicas: {{ .Values.hpacore.minReplicas }}
  maxReplicas: {{ .Values.hpacore.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.hpacore.cpuUtilization }}
