apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}

spec:
  tls:
    - hosts:
        - core.osstorresk8s.com
        - analytics.osstorresk8s.com
      secretName: cert-manager-webhook-ca
  rules:
    - host: core.osstorresk8s.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: core-service
                port:
                  number: 8000
    - host: analytics.osstorresk8s.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: analytics-service
                port:
                  number: 8001