apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-secrets
  namespace: default
spec:
  provider: aws
  secretObjects:
  - secretName: application-secrets
    type: Opaque
    data:
    - objectName: DJANGO_CONFIGURATION
      key: DJANGO_CONFIGURATION
    - objectName: DJANGO_CELERY_BROKER_URL
      key: DJANGO_CELERY_BROKER_URL
    - objectName: DJANGO_CELERY_RESULT_BACKEND
      key: DJANGO_CELERY_RESULT_BACKEND
    - objectName: DATABASE_URL
      key: DATABASE_URL
    - objectName: CACHE_LOCATION
      key: CACHE_LOCATION
  parameters:
    objects: |
      - objectName: application-secrets 
        objectType: secretsmanager
        jmesPath:
          - path: DJANGO_CONFIGURATION
            objectAlias: DJANGO_CONFIGURATION
          - path: DJANGO_CELERY_BROKER_URL
            objectAlias: DJANGO_CELERY_BROKER_URL
          - path: DJANGO_CELERY_RESULT_BACKEND
            objectAlias: DJANGO_CELERY_RESULT_BACKEND
          - path: DATABASE_URL
            objectAlias: DATABASE_URL
          - path: CACHE_LOCATION
            objectAlias: CACHE_LOCATION
