apiVersion: v1
kind: Service
metadata:
  name: core-service
  namespace: default
spec:
  type: {{ .Values.coreservice.type }}
  selector:
    app: core
  ports:
  - protocol: TCP
    port: {{ .Values.coreservice.port }}
    targetPort: 8000
