# An example of ClusterConfig object using Managed Nodes
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig


metadata:
  name: core-applications
  region: us-west-2
  version: "1.30"

iam:
  withOIDC: true
  serviceAccounts:
    - metadata:
        name: secrets-manager-access-sa
        namespace: default
      attachPolicyARNs:
        - arn:aws:iam::account_id:policy/EKSSecretsManagerPolicy
      roleName: eks-secrets-manager-role

managedNodeGroups:
  - name: managed-ng-core
    instanceType: t2.medium
    minSize: 1
    desiredCapacity: 2
    maxSize: 5
    availabilityZones: ["us-west-2a", "us-west-2b"]
    volumeSize: 20
    updateConfig:
      maxUnavailable: 2
    iam:
      withAddonPolicies:
        externalDNS: true
        certManager: true
        albIngress: true
    ssh:
      enableSsm: true
    securityGroups:
      attachIDs: ["sg_id"]

vpc:
  id: "vpc_id"
  subnets:
    private:
      us-west-2a: { id: "subnet_id" }
      us-west-2b: { id: "subnet_id" }
    public:
      us-west-2a: { id: "subnet_id" }
      us-west-2b: { id: "subnet_id" }


